//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveCadwallader.CodeMaid.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteveCadwallader.CodeMaid.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Access levels should be ordered by 的本地化字符串。
        /// </summary>
        public static string AccessLevelsShouldBeOrderedBy {
            get {
                return ResourceManager.GetString("AccessLevelsShouldBeOrderedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 access then type 的本地化字符串。
        /// </summary>
        public static string AccessThenType {
            get {
                return ResourceManager.GetString("AccessThenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add space inside self closing tags 的本地化字符串。
        /// </summary>
        public static string AddSpaceInsideSelfClosingTags {
            get {
                return ResourceManager.GetString("AddSpaceInsideSelfClosingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add spacing around XML tags 的本地化字符串。
        /// </summary>
        public static string AddSpacingAroundXMLTags {
            get {
                return ResourceManager.GetString("AddSpacingAroundXMLTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after attributes 的本地化字符串。
        /// </summary>
        public static string AfterAttributes {
            get {
                return ResourceManager.GetString("AfterAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after opening braces 的本地化字符串。
        /// </summary>
        public static string AfterOpeningBraces {
            get {
                return ResourceManager.GetString("AfterOpeningBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alert threshold 的本地化字符串。
        /// </summary>
        public static string AlertThreshold {
            get {
                return ResourceManager.GetString("AlertThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align XML &amp;lt;param&amp;gt; tags 的本地化字符串。
        /// </summary>
        public static string AlignXMLLtParamGtTags {
            get {
                return ResourceManager.GetString("AlignXMLLtParamGtTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 alphabetical 的本地化字符串。
        /// </summary>
        public static string Alphabetical {
            get {
                return ResourceManager.GetString("Alphabetical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alphabetize members of the same group 的本地化字符串。
        /// </summary>
        public static string AlphabetizeMembersOfTheSameGroup {
            get {
                return ResourceManager.GetString("AlphabetizeMembersOfTheSameGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always split all XML tags onto multiple lines 的本地化字符串。
        /// </summary>
        public static string AlwaysSplitAllXMLTagsOntoMultipleLines {
            get {
                return ResourceManager.GetString("AlwaysSplitAllXMLTagsOntoMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always split &amp;lt;summary&amp;gt; tags onto multiple lines 的本地化字符串。
        /// </summary>
        public static string AlwaysSplitLtSummaryGtTagsOntoMultipleLines {
            get {
                return ResourceManager.GetString("AlwaysSplitLtSummaryGtTagsOntoMultipleLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you ready for CodeMaid to clean everything in the solution? 的本地化字符串。
        /// </summary>
        public static string AreYouReadyForCodeMaidToCleanEverythingInTheSolution {
            get {
                return ResourceManager.GetString("AreYouReadyForCodeMaidToCleanEverythingInTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at bottom of file 的本地化字符串。
        /// </summary>
        public static string AtBottomOfFile {
            get {
                return ResourceManager.GetString("AtBottomOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at top of file 的本地化字符串。
        /// </summary>
        public static string AtTopOfFile {
            get {
                return ResourceManager.GetString("AtTopOfFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic 的本地化字符串。
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically run cleanup on file save 的本地化字符串。
        /// </summary>
        public static string AutomaticallyRunCleanupOnFileSave {
            get {
                return ResourceManager.GetString("AutomaticallyRunCleanupOnFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically save and close documents opened by cleanup 的本地化字符串。
        /// </summary>
        public static string AutomaticallySaveAndCloseDocumentsOpenedByCleanup {
            get {
                return ResourceManager.GetString("AutomaticallySaveAndCloseDocumentsOpenedByCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic Cleanup On Save -  的本地化字符串。
        /// </summary>
        public static string AutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("AutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch  的本地化字符串。
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 before closing angle brackets 的本地化字符串。
        /// </summary>
        public static string BeforeClosingAngleBrackets {
            get {
                return ResourceManager.GetString("BeforeClosingAngleBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 before closing braces 的本地化字符串。
        /// </summary>
        public static string BeforeClosingBraces {
            get {
                return ResourceManager.GetString("BeforeClosingBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 before closing tags 的本地化字符串。
        /// </summary>
        public static string BeforeClosingTags {
            get {
                return ResourceManager.GetString("BeforeClosingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 between chained statements 的本地化字符串。
        /// </summary>
        public static string BetweenChainedStatements {
            get {
                return ResourceManager.GetString("BetweenChainedStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Building 的本地化字符串。
        /// </summary>
        public static string Building {
            get {
                return ResourceManager.GetString("Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build Progress 的本地化字符串。
        /// </summary>
        public static string BuildProgress {
            get {
                return ResourceManager.GetString("BuildProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Build progress window 的本地化字符串。
        /// </summary>
        public static string BuildProgressWindow {
            get {
                return ResourceManager.GetString("BuildProgressWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache file code models 的本地化字符串。
        /// </summary>
        public static string CacheFileCodeModels {
            get {
                return ResourceManager.GetString("CacheFileCodeModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canceling... 的本地化字符串。
        /// </summary>
        public static string Canceling {
            get {
                return ResourceManager.GetString("Canceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleaning 的本地化字符串。
        /// </summary>
        public static string Cleaning {
            get {
                return ResourceManager.GetString("Cleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Types 的本地化字符串。
        /// </summary>
        public static string CleaningFileTypesViewModel_FileTypes {
            get {
                return ResourceManager.GetString("CleaningFileTypesViewModel_FileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string CleaningUpdateViewModel_Update {
            get {
                return ResourceManager.GetString("CleaningUpdateViewModel_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleanup 的本地化字符串。
        /// </summary>
        public static string Cleanup {
            get {
                return ResourceManager.GetString("Cleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cleanup cannot run while debugging. 的本地化字符串。
        /// </summary>
        public static string CleanupCannotRunWhileDebugging {
            get {
                return ResourceManager.GetString("CleanupCannotRunWhileDebugging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Solution Explorer search filtering to find filtered items 的本地化字符串。
        /// </summary>
        public static string ClearSolutionExplorerSearchFilteringToFindFilteredItems {
            get {
                return ResourceManager.GetString("ClearSolutionExplorerSearchFilteringToFindFilteredItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Cleanup All Code 的本地化字符串。
        /// </summary>
        public static string CodeMaidCleanupAllCode {
            get {
                return ResourceManager.GetString("CodeMaidCleanupAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Cleanup External File 的本地化字符串。
        /// </summary>
        public static string CodeMaidCleanupExternalFile {
            get {
                return ResourceManager.GetString("CodeMaidCleanupExternalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Cleanup Progress 的本地化字符串。
        /// </summary>
        public static string CodeMaidCleanupProgress {
            get {
                return ResourceManager.GetString("CodeMaidCleanupProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Confirmation for Cleanup All Code 的本地化字符串。
        /// </summary>
        public static string CodeMaidConfirmationForCleanupAllCode {
            get {
                return ResourceManager.GetString("CodeMaidConfirmationForCleanupAllCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid did not find a non-code comment {0} to reformat. 的本地化字符串。
        /// </summary>
        public static string CodeMaidDidNotFindANonCodeComment0ToReformat {
            get {
                return ResourceManager.GetString("CodeMaidDidNotFindANonCodeComment0ToReformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Export  的本地化字符串。
        /// </summary>
        public static string CodeMaidExport {
            get {
                return ResourceManager.GetString("CodeMaidExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid failed to load theme &apos;{0}&apos;.  See output window for more details. 的本地化字符串。
        /// </summary>
        public static string CodeMaidFailedToLoadTheme0SeeOutputWindowForMoreDetails {
            get {
                return ResourceManager.GetString("CodeMaidFailedToLoadTheme0SeeOutputWindowForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid finished formatting the comment. 的本地化字符串。
        /// </summary>
        public static string CodeMaidFinishedFormattingTheComment {
            get {
                return ResourceManager.GetString("CodeMaidFinishedFormattingTheComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid finished formatting the comments {0}. 的本地化字符串。
        /// </summary>
        public static string CodeMaidFinishedFormattingTheComments0 {
            get {
                return ResourceManager.GetString("CodeMaidFinishedFormattingTheComments0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid Format Comment 的本地化字符串。
        /// </summary>
        public static string CodeMaidFormatComment {
            get {
                return ResourceManager.GetString("CodeMaidFormatComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid has successfully exported  的本地化字符串。
        /// </summary>
        public static string CodeMaidHasSuccessfullyExported {
            get {
                return ResourceManager.GetString("CodeMaidHasSuccessfullyExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid: Import  的本地化字符串。
        /// </summary>
        public static string CodeMaidImport {
            get {
                return ResourceManager.GetString("CodeMaidImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid Options 的本地化字符串。
        /// </summary>
        public static string CodeMaidOptions {
            get {
                return ResourceManager.GetString("CodeMaidOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid Spade 的本地化字符串。
        /// </summary>
        public static string CodeMaidSpade {
            get {
                return ResourceManager.GetString("CodeMaidSpade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid turned automatic cleanup on save 的本地化字符串。
        /// </summary>
        public static string CodeMaidTurnedAutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("CodeMaidTurnedAutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CodeMaid was unable to export  的本地化字符串。
        /// </summary>
        public static string CodeMaidWasUnableToExport {
            get {
                return ResourceManager.GetString("CodeMaidWasUnableToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse solutions when they are opened 的本地化字符串。
        /// </summary>
        public static string CollapseSolutionsWhenTheyAreOpened {
            get {
                return ResourceManager.GetString("CollapseSolutionsWhenTheyAreOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapsing 的本地化字符串。
        /// </summary>
        public static string CollapsingViewModel_Collapsing {
            get {
                return ResourceManager.GetString("CollapsingViewModel_Collapsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Conditions 的本地化字符串。
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Config files (*.config)|*.config|All Files (*.*)|*.* 的本地化字符串。
        /// </summary>
        public static string ConfigFilesConfigConfigAllFiles {
            get {
                return ResourceManager.GetString("ConfigFilesConfigConfigAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deploying 的本地化字符串。
        /// </summary>
        public static string Deploying {
            get {
                return ResourceManager.GetString("Deploying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnostics 的本地化字符串。
        /// </summary>
        public static string Diagnostics {
            get {
                return ResourceManager.GetString("Diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagnostics mode 的本地化字符串。
        /// </summary>
        public static string DiagnosticsMode {
            get {
                return ResourceManager.GetString("DiagnosticsMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Digging (Spade) 的本地化字符串。
        /// </summary>
        public static string DiggingViewModel_DiggingSpade {
            get {
                return ResourceManager.GetString("DiggingViewModel_DiggingSpade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display 的本地化字符串。
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you want to perform a partial cleanup? 的本地化字符串。
        /// </summary>
        public static string DoYouWantToPerformAPartialCleanup {
            get {
                return ResourceManager.GetString("DoYouWantToPerformAPartialCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to reorder, drag over to group, right click to split, double-click to rename 的本地化字符串。
        /// </summary>
        public static string DragToReorderDragOverToGroupRightClickToSplitDoubleClickToRename {
            get {
                return ResourceManager.GetString("DragToReorderDragOverToGroupRightClickToSplitDoubleClickToRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Everything else (ex: .txt, README) 的本地化字符串。
        /// </summary>
        public static string EverythingElseExTxtREADME {
            get {
                return ResourceManager.GetString("EverythingElseExTxtREADME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exclude 的本地化字符串。
        /// </summary>
        public static string Exclude {
            get {
                return ResourceManager.GetString("Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ex: #endregion Methods 的本地化字符串。
        /// </summary>
        public static string ExEndregionMethods {
            get {
                return ResourceManager.GetString("ExEndregionMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ex: #region Public Methods, #region Private Methods 的本地化字符串。
        /// </summary>
        public static string ExRegionPublicMethodsRegionPrivateMethods {
            get {
                return ResourceManager.GetString("ExRegionPublicMethodsRegionPrivateMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 External 的本地化字符串。
        /// </summary>
        public static string External {
            get {
                return ResourceManager.GetString("External", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extra indent for values inside XML comments 的本地化字符串。
        /// </summary>
        public static string ExtraIndentForValuesInsideXMLComments {
            get {
                return ResourceManager.GetString("ExtraIndentForValuesInsideXMLComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Header 的本地化字符串。
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 file order 的本地化字符串。
        /// </summary>
        public static string FileOrder {
            get {
                return ResourceManager.GetString("FileOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finding 的本地化字符串。
        /// </summary>
        public static string FindingViewModel_Finding {
            get {
                return ResourceManager.GetString("FindingViewModel_Finding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Formatting 的本地化字符串。
        /// </summary>
        public static string FormattingViewModel_Formatting {
            get {
                return ResourceManager.GetString("FormattingViewModel_Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide build progress window when a build stops 的本地化字符串。
        /// </summary>
        public static string HideBuildProgressWindowWhenABuildStops {
            get {
                return ResourceManager.GetString("HideBuildProgressWindowWhenABuildStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icons 的本地化字符串。
        /// </summary>
        public static string Icons {
            get {
                return ResourceManager.GetString("Icons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If there is only one project in a solution, keep it expanded but still collapse its children 的本地化字符串。
        /// </summary>
        public static string IfThereIsOnlyOneProjectInASolutionKeepItExpandedButStillCollapseItsChildren {
            get {
                return ResourceManager.GetString("IfThereIsOnlyOneProjectInASolutionKeepItExpandedButStillCollapseItsChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import 的本地化字符串。
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Include access level in regions 的本地化字符串。
        /// </summary>
        public static string IncludeAccessLevelInRegions {
            get {
                return ResourceManager.GetString("IncludeAccessLevelInRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indentation margin 的本地化字符串。
        /// </summary>
        public static string IndentationMargin {
            get {
                return ResourceManager.GetString("IndentationMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert blank line padding after 的本地化字符串。
        /// </summary>
        public static string InsertBlankLinePaddingAfter {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert blank line padding before 的本地化字符串。
        /// </summary>
        public static string InsertBlankLinePaddingBefore {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert blank line padding between 的本地化字符串。
        /// </summary>
        public static string InsertBlankLinePaddingBetween {
            get {
                return ResourceManager.GetString("InsertBlankLinePaddingBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert blank space before 的本地化字符串。
        /// </summary>
        public static string InsertBlankSpaceBefore {
            get {
                return ResourceManager.GetString("InsertBlankSpaceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert end of file trailing new line 的本地化字符串。
        /// </summary>
        public static string InsertEndOfFileTrailingNewLine {
            get {
                return ResourceManager.GetString("InsertEndOfFileTrailingNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert explicit access modifiers on 的本地化字符串。
        /// </summary>
        public static string InsertExplicitAccessModifiersOn {
            get {
                return ResourceManager.GetString("InsertExplicitAccessModifiersOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert/keep regions even if they are empty 的本地化字符串。
        /// </summary>
        public static string InsertKeepRegionsEvenIfTheyAreEmpty {
            get {
                return ResourceManager.GetString("InsertKeepRegionsEvenIfTheyAreEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert new regions 的本地化字符串。
        /// </summary>
        public static string InsertNewRegions {
            get {
                return ResourceManager.GetString("InsertNewRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in the selection 的本地化字符串。
        /// </summary>
        public static string InTheSelection {
            get {
                return ResourceManager.GetString("InTheSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  is not in the solution so some cleanup actions may be unavailable. 的本地化字符串。
        /// </summary>
        public static string IsNotInTheSolutionSoSomeCleanupActionsMayBeUnavailable {
            get {
                return ResourceManager.GetString("IsNotInTheSolutionSoSomeCleanupActionsMayBeUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep members within regions 的本地化字符串。
        /// </summary>
        public static string KeepMembersWithinRegions {
            get {
                return ResourceManager.GetString("KeepMembersWithinRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep XML tags together 的本地化字符串。
        /// </summary>
        public static string KeepXMLTagsTogether {
            get {
                return ResourceManager.GetString("KeepXMLTagsTogether", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load models asynchronously 的本地化字符串。
        /// </summary>
        public static string LoadModelsAsynchronously {
            get {
                return ResourceManager.GetString("LoadModelsAsynchronously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Member type order, grouping and preferred names 的本地化字符串。
        /// </summary>
        public static string MemberTypeOrderGroupingAndPreferredNames {
            get {
                return ResourceManager.GetString("MemberTypeOrderGroupingAndPreferredNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Miscellaneous 的本地化字符串。
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 name only 的本地化字符串。
        /// </summary>
        public static string NameOnly {
            get {
                return ResourceManager.GetString("NameOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        public static string Navigation {
            get {
                return ResourceManager.GetString("Navigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Region 的本地化字符串。
        /// </summary>
        public static string NewRegion {
            get {
                return ResourceManager.GetString("NewRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other cleaning commands (ex: ReSharper.ReSharper_SilentCleanupCode) 的本地化字符串。
        /// </summary>
        public static string OtherCleaningCommandsExReSharperReSharper_SilentCleanupCode {
            get {
                return ResourceManager.GetString("OtherCleaningCommandsExReSharperReSharper_SilentCleanupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performance 的本地化字符串。
        /// </summary>
        public static string Performance {
            get {
                return ResourceManager.GetString("Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform partial cleanup if file is not in the solution 的本地化字符串。
        /// </summary>
        public static string PerformPartialCleanupIfFileIsNotInTheSolution {
            get {
                return ResourceManager.GetString("PerformPartialCleanupIfFileIsNotInTheSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perform reorganization when preprocessor conditionals are present 的本地化字符串。
        /// </summary>
        public static string PerformReorganizationWhenPreprocessorConditionalsArePresent {
            get {
                return ResourceManager.GetString("PerformReorganizationWhenPreprocessorConditionalsArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place each command on a separate line 的本地化字符串。
        /// </summary>
        public static string PlaceEachCommandOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachCommandOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place each regular expression on a separate line 的本地化字符串。
        /// </summary>
        public static string PlaceEachRegularExpressionOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachRegularExpressionOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place each set on a separate line 的本地化字符串。
        /// </summary>
        public static string PlaceEachSetOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachSetOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place each using statement on a separate line 的本地化字符串。
        /// </summary>
        public static string PlaceEachUsingStatementOnASeparateLine {
            get {
                return ResourceManager.GetString("PlaceEachUsingStatementOnASeparateLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Place explicit interface members at the end of their group 的本地化字符串。
        /// </summary>
        public static string PlaceExplicitInterfaceMembersAtTheEndOfTheirGroup {
            get {
                return ResourceManager.GetString("PlaceExplicitInterfaceMembersAtTheEndOfTheirGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary ordering should be by 的本地化字符串。
        /// </summary>
        public static string PrimaryOrderingShouldBeBy {
            get {
                return ResourceManager.GetString("PrimaryOrderingShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary sort should be by 的本地化字符串。
        /// </summary>
        public static string PrimarySortShouldBeBy {
            get {
                return ResourceManager.GetString("PrimarySortShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Progressing 的本地化字符串。
        /// </summary>
        public static string ProgressingViewModel_Progressing {
            get {
                return ResourceManager.GetString("ProgressingViewModel_Progressing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rebuilding 的本地化字符串。
        /// </summary>
        public static string Rebuilding {
            get {
                return ResourceManager.GetString("Rebuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regions 的本地化字符串。
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Regular expressions that match path names to exclude  (ex: \.resx$ or \\lib\\ ) 的本地化字符串。
        /// </summary>
        public static string RegularExpressionsThatMatchPathNamesToExcludeExResxOrLib {
            get {
                return ResourceManager.GetString("RegularExpressionsThatMatchPathNamesToExcludeExResxOrLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove 的本地化字符串。
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove All Regions 的本地化字符串。
        /// </summary>
        public static string RemoveAllRegions {
            get {
                return ResourceManager.GetString("RemoveAllRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove blank lines 的本地化字符串。
        /// </summary>
        public static string RemoveBlankLines {
            get {
                return ResourceManager.GetString("RemoveBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove blank spaces 的本地化字符串。
        /// </summary>
        public static string RemoveBlankSpaces {
            get {
                return ResourceManager.GetString("RemoveBlankSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove Current Region 的本地化字符串。
        /// </summary>
        public static string RemoveCurrentRegion {
            get {
                return ResourceManager.GetString("RemoveCurrentRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove end of file trailing new line 的本地化字符串。
        /// </summary>
        public static string RemoveEndOfFileTrailingNewLine {
            get {
                return ResourceManager.GetString("RemoveEndOfFileTrailingNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove end of line whitespace 的本地化字符串。
        /// </summary>
        public static string RemoveEndOfLineWhitespace {
            get {
                return ResourceManager.GetString("RemoveEndOfLineWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove existing regions 的本地化字符串。
        /// </summary>
        public static string RemoveExistingRegions {
            get {
                return ResourceManager.GetString("RemoveExistingRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove multiple consecutive blank lines 的本地化字符串。
        /// </summary>
        public static string RemoveMultipleConsecutiveBlankLines {
            get {
                return ResourceManager.GetString("RemoveMultipleConsecutiveBlankLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove regions 的本地化字符串。
        /// </summary>
        public static string RemoveRegions {
            get {
                return ResourceManager.GetString("RemoveRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;Remove Selected Regions 的本地化字符串。
        /// </summary>
        public static string RemoveSelectedRegions {
            get {
                return ResourceManager.GetString("RemoveSelectedRegions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reorganizing 的本地化字符串。
        /// </summary>
        public static string Reorganizing {
            get {
                return ResourceManager.GetString("Reorganizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types 的本地化字符串。
        /// </summary>
        public static string ReorganizingTypesViewModel_Types {
            get {
                return ResourceManager.GetString("ReorganizingTypesViewModel_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset to Defaults 的本地化字符串。
        /// </summary>
        public static string ResetToDefaults {
            get {
                return ResourceManager.GetString("ResetToDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run format comments during cleanup 的本地化字符串。
        /// </summary>
        public static string RunFormatCommentsDuringCleanup {
            get {
                return ResourceManager.GetString("RunFormatCommentsDuringCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run format document 的本地化字符串。
        /// </summary>
        public static string RunFormatDocument {
            get {
                return ResourceManager.GetString("RunFormatDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run JetBrains ReSharper cleanup 的本地化字符串。
        /// </summary>
        public static string RunJetBrainsReSharperCleanup {
            get {
                return ResourceManager.GetString("RunJetBrainsReSharperCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run remove and sort using statements 的本地化字符串。
        /// </summary>
        public static string RunRemoveAndSortUsingStatements {
            get {
                return ResourceManager.GetString("RunRemoveAndSortUsingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run reorganize at start of cleanup 的本地化字符串。
        /// </summary>
        public static string RunReorganizeAtStartOfCleanup {
            get {
                return ResourceManager.GetString("RunReorganizeAtStartOfCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Telerik JustCode cleanup 的本地化字符串。
        /// </summary>
        public static string RunTelerikJustCodeCleanup {
            get {
                return ResourceManager.GetString("RunTelerikJustCodeCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run XAML Styler cleanup 的本地化字符串。
        /// </summary>
        public static string RunXAMLStylerCleanup {
            get {
                return ResourceManager.GetString("RunXAMLStylerCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search CodeMaid Spade (Ctrl+M, ;) 的本地化字符串。
        /// </summary>
        public static string SearchCodeMaidSpadeCtrlM {
            get {
                return ResourceManager.GetString("SearchCodeMaidSpadeCtrlM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .  See output window for more details. 的本地化字符串。
        /// </summary>
        public static string SeeOutputWindowForMoreDetails {
            get {
                return ResourceManager.GetString("SeeOutputWindowForMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select a sub-category to set options. 的本地化字符串。
        /// </summary>
        public static string SelectASubCategoryToSetOptions {
            get {
                return ResourceManager.GetString("SelectASubCategoryToSetOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets of related file extensions  (ex: .cpp .h ) 的本地化字符串。
        /// </summary>
        public static string SetsOfRelatedFileExtensionsExCppH {
            get {
                return ResourceManager.GetString("SetsOfRelatedFileExtensionsExCppH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OFF 的本地化字符串。
        /// </summary>
        public static string SettingCleanupOnSaveCommand_OFF {
            get {
                return ResourceManager.GetString("SettingCleanupOnSaveCommand_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ON 的本地化字符串。
        /// </summary>
        public static string SettingCleanupOnSaveCommand_ON {
            get {
                return ResourceManager.GetString("SettingCleanupOnSaveCommand_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show build progress on Visual Studio icon in Windows taskbar 的本地化字符串。
        /// </summary>
        public static string ShowBuildProgressOnVisualStudioIconInWindowsTaskbar {
            get {
                return ResourceManager.GetString("ShowBuildProgressOnVisualStudioIconInWindowsTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show build progress window when a build starts 的本地化字符串。
        /// </summary>
        public static string ShowBuildProgressWindowWhenABuildStarts {
            get {
                return ResourceManager.GetString("ShowBuildProgressWindowWhenABuildStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item complexity (McCabe) 的本地化字符串。
        /// </summary>
        public static string ShowItemComplexityMcCabe {
            get {
                return ResourceManager.GetString("ShowItemComplexityMcCabe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show item metadata 的本地化字符串。
        /// </summary>
        public static string ShowItemMetadata {
            get {
                return ResourceManager.GetString("ShowItemMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show method parameters 的本地化字符串。
        /// </summary>
        public static string ShowMethodParameters {
            get {
                return ResourceManager.GetString("ShowMethodParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show start page when a solution is closed 的本地化字符串。
        /// </summary>
        public static string ShowStartPageWhenASolutionIsClosed {
            get {
                return ResourceManager.GetString("ShowStartPageWhenASolutionIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip during automatic cleanup on save 的本地化字符串。
        /// </summary>
        public static string SkipDuringAutomaticCleanupOnSave {
            get {
                return ResourceManager.GetString("SkipDuringAutomaticCleanupOnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skip wrapping on the last word 的本地化字符串。
        /// </summary>
        public static string SkipWrappingOnTheLastWord {
            get {
                return ResourceManager.GetString("SkipWrappingOnTheLastWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Solution-Specific Settings 的本地化字符串。
        /// </summary>
        public static string SolutionSpecificSettings {
            get {
                return ResourceManager.GetString("SolutionSpecificSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort 的本地化字符串。
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split 的本地化字符串。
        /// </summary>
        public static string Split {
            get {
                return ResourceManager.GetString("Split", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Successful 的本地化字符串。
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S&amp;witch File 的本地化字符串。
        /// </summary>
        public static string SWitchFile {
            get {
                return ResourceManager.GetString("SWitchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switching 的本地化字符串。
        /// </summary>
        public static string SwitchingViewModel_Switching {
            get {
                return ResourceManager.GetString("SwitchingViewModel_Switching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 S&amp;witch to  的本地化字符串。
        /// </summary>
        public static string SWitchTo {
            get {
                return ResourceManager.GetString("SWitchTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Synchronize outlining with the code file 的本地化字符串。
        /// </summary>
        public static string SynchronizeOutliningWithTheCodeFile {
            get {
                return ResourceManager.GetString("SynchronizeOutliningWithTheCodeFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T4 generated code 的本地化字符串。
        /// </summary>
        public static string T4GeneratedCode {
            get {
                return ResourceManager.GetString("T4GeneratedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Temporarily open solution folders to find nested items 的本地化字符串。
        /// </summary>
        public static string TemporarilyOpenSolutionFoldersToFindNestedItems {
            get {
                return ResourceManager.GetString("TemporarilyOpenSolutionFoldersToFindNestedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Theme 的本地化字符串。
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Third Party 的本地化字符串。
        /// </summary>
        public static string ThirdPartyViewModel_ThirdParty {
            get {
                return ResourceManager.GetString("ThirdPartyViewModel_ThirdParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  to &apos;{0}&apos;. 的本地化字符串。
        /// </summary>
        public static string To0 {
            get {
                return ResourceManager.GetString("To0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type 的本地化字符串。
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type then access 的本地化字符串。
        /// </summary>
        public static string TypeThenAccess {
            get {
                return ResourceManager.GetString("TypeThenAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to toggle read only state on  的本地化字符串。
        /// </summary>
        public static string UnableToToggleReadOnlyStateOn {
            get {
                return ResourceManager.GetString("UnableToToggleReadOnlyStateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 under the cursor 的本地化字符串。
        /// </summary>
        public static string UnderTheCursor {
            get {
                return ResourceManager.GetString("UnderTheCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Unsuccessful 的本地化字符串。
        /// </summary>
        public static string Unsuccessful {
            get {
                return ResourceManager.GetString("Unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update accessors to both be single-line or multi-line (SA1504) 的本地化字符串。
        /// </summary>
        public static string UpdateAccessorsToBothBeSingleLineOrMultiLineSA1504 {
            get {
                return ResourceManager.GetString("UpdateAccessorsToBothBeSingleLineOrMultiLineSA1504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update #endregion tags with region name 的本地化字符串。
        /// </summary>
        public static string UpdateEndregionTagsWithRegionName {
            get {
                return ResourceManager.GetString("UpdateEndregionTagsWithRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update single line methods by placing braces on separate lines (SA1502) 的本地化字符串。
        /// </summary>
        public static string UpdateSingleLineMethodsByPlacingBracesOnSeparateLinesSA1502 {
            get {
                return ResourceManager.GetString("UpdateSingleLineMethodsByPlacingBracesOnSeparateLinesSA1502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Settings 的本地化字符串。
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use undo transactions 的本地化字符串。
        /// </summary>
        public static string UseUndoTransactions {
            get {
                return ResourceManager.GetString("UseUndoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Using statements to re-insert when removed  (ex: using System; ) 的本地化字符串。
        /// </summary>
        public static string UsingStatementsToReInsertWhenRemovedExUsingSystem {
            get {
                return ResourceManager.GetString("UsingStatementsToReInsertWhenRemovedExUsingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Visuals 的本地化字符串。
        /// </summary>
        public static string Visuals {
            get {
                return ResourceManager.GetString("Visuals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning threshold 的本地化字符串。
        /// </summary>
        public static string WarningThreshold {
            get {
                return ResourceManager.GetString("WarningThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When navigating center on 的本地化字符串。
        /// </summary>
        public static string WhenNavigatingCenterOn {
            get {
                return ResourceManager.GetString("WhenNavigatingCenterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When sorting by type, secondary sort should be by 的本地化字符串。
        /// </summary>
        public static string WhenSortingByTypeSecondarySortShouldBeBy {
            get {
                return ResourceManager.GetString("WhenSortingByTypeSecondarySortShouldBeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 While Cleaning 的本地化字符串。
        /// </summary>
        public static string WhileCleaning {
            get {
                return ResourceManager.GetString("WhileCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whitespace 的本地化字符串。
        /// </summary>
        public static string Whitespace {
            get {
                return ResourceManager.GetString("Whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 whole item 的本地化字符串。
        /// </summary>
        public static string WholeItem {
            get {
                return ResourceManager.GetString("WholeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows taskbar 的本地化字符串。
        /// </summary>
        public static string WindowsTaskbar {
            get {
                return ResourceManager.GetString("WindowsTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrap comments at column 的本地化字符串。
        /// </summary>
        public static string WrapCommentsAtColumn {
            get {
                return ResourceManager.GetString("WrapCommentsAtColumn", resourceCulture);
            }
        }
    }
}
