//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveCadwallader.CodeMaid.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Progressing_ShowBuildProgressOnBuildStart {
            get {
                return ((bool)(this["Progressing_ShowBuildProgressOnBuildStart"]));
            }
            set {
                this["Progressing_ShowBuildProgressOnBuildStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Progressing_HideBuildProgressOnBuildStop {
            get {
                return ((bool)(this["Progressing_HideBuildProgressOnBuildStop"]));
            }
            set {
                this["Progressing_HideBuildProgressOnBuildStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reorganizing_AlphabetizeMembersOfTheSameGroup {
            get {
                return ((bool)(this["Reorganizing_AlphabetizeMembersOfTheSameGroup"]));
            }
            set {
                this["Reorganizing_AlphabetizeMembersOfTheSameGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RunAtStartOfCleanup {
            get {
                return ((bool)(this["Reorganizing_RunAtStartOfCleanup"]));
            }
            set {
                this["Reorganizing_RunAtStartOfCleanup"] = value;
            }
        }
    }
}
