//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveCadwallader.CodeMaid.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_AutoCleanupOnFileSave {
            get {
                return ((bool)(this["Cleaning_AutoCleanupOnFileSave"]));
            }
            set {
                this["Cleaning_AutoCleanupOnFileSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_AutoSaveAndCloseIfOpenedByCleanup {
            get {
                return ((bool)(this["Cleaning_AutoSaveAndCloseIfOpenedByCleanup"]));
            }
            set {
                this["Cleaning_AutoSaveAndCloseIfOpenedByCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_ExcludeT4GeneratedCode {
            get {
                return ((bool)(this["Cleaning_ExcludeT4GeneratedCode"]));
            }
            set {
                this["Cleaning_ExcludeT4GeneratedCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\.Designer\\.cs$||\\.Designer\\.vb$||\\.resx$||\\.min\\.css$||\\.min\\.js$")]
        public string Cleaning_ExclusionExpression {
            get {
                return ((string)(this["Cleaning_ExclusionExpression"]));
            }
            set {
                this["Cleaning_ExclusionExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeCPlusPlus {
            get {
                return ((bool)(this["Cleaning_IncludeCPlusPlus"]));
            }
            set {
                this["Cleaning_IncludeCPlusPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeCSharp {
            get {
                return ((bool)(this["Cleaning_IncludeCSharp"]));
            }
            set {
                this["Cleaning_IncludeCSharp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeCSS {
            get {
                return ((bool)(this["Cleaning_IncludeCSS"]));
            }
            set {
                this["Cleaning_IncludeCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_IncludeEverythingElse {
            get {
                return ((bool)(this["Cleaning_IncludeEverythingElse"]));
            }
            set {
                this["Cleaning_IncludeEverythingElse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeFSharp {
            get {
                return ((bool)(this["Cleaning_IncludeFSharp"]));
            }
            set {
                this["Cleaning_IncludeFSharp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeHTML {
            get {
                return ((bool)(this["Cleaning_IncludeHTML"]));
            }
            set {
                this["Cleaning_IncludeHTML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeJavaScript {
            get {
                return ((bool)(this["Cleaning_IncludeJavaScript"]));
            }
            set {
                this["Cleaning_IncludeJavaScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeJSON {
            get {
                return ((bool)(this["Cleaning_IncludeJSON"]));
            }
            set {
                this["Cleaning_IncludeJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeLESS {
            get {
                return ((bool)(this["Cleaning_IncludeLESS"]));
            }
            set {
                this["Cleaning_IncludeLESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludePHP {
            get {
                return ((bool)(this["Cleaning_IncludePHP"]));
            }
            set {
                this["Cleaning_IncludePHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludePowerShell {
            get {
                return ((bool)(this["Cleaning_IncludePowerShell"]));
            }
            set {
                this["Cleaning_IncludePowerShell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeR {
            get {
                return ((bool)(this["Cleaning_IncludeR"]));
            }
            set {
                this["Cleaning_IncludeR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeSCSS {
            get {
                return ((bool)(this["Cleaning_IncludeSCSS"]));
            }
            set {
                this["Cleaning_IncludeSCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeTypeScript {
            get {
                return ((bool)(this["Cleaning_IncludeTypeScript"]));
            }
            set {
                this["Cleaning_IncludeTypeScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeVB {
            get {
                return ((bool)(this["Cleaning_IncludeVB"]));
            }
            set {
                this["Cleaning_IncludeVB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeXAML {
            get {
                return ((bool)(this["Cleaning_IncludeXAML"]));
            }
            set {
                this["Cleaning_IncludeXAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_IncludeXML {
            get {
                return ((bool)(this["Cleaning_IncludeXML"]));
            }
            set {
                this["Cleaning_IncludeXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterClasses {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterClasses"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterDelegates {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterDelegates"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterDelegates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterEndRegionTags {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterEndRegionTags"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterEndRegionTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterEnumerations {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterEnumerations"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterEnumerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterEvents {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterEvents"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterFieldsMultiLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterFieldsMultiLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterFieldsMultiLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterInterfaces {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterInterfaces"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterMethods {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterMethods"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterNamespaces {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterNamespaces"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterPropertiesMultiLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterPropertiesMultiLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterPropertiesMultiLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingAfterPropertiesSingleLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterPropertiesSingleLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterPropertiesSingleLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterRegionTags {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterRegionTags"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterRegionTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterStructs {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterStructs"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterStructs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingAfterUsingStatementBlocks {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterUsingStatementBlocks"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterUsingStatementBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeCaseStatements {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeCaseStatements"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeCaseStatements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeClasses {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeClasses"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeDelegates {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeDelegates"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeDelegates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeEndRegionTags {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeEndRegionTags"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeEndRegionTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeEnumerations {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeEnumerations"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeEnumerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeEvents {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeEvents"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeFieldsMultiLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeFieldsMultiLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeFieldsMultiLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeInterfaces {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeInterfaces"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeMethods {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeMethods"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeNamespaces {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeNamespaces"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeNamespaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforePropertiesMultiLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforePropertiesMultiLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforePropertiesMultiLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingBeforePropertiesSingleLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforePropertiesSingleLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforePropertiesSingleLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeRegionTags {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeRegionTags"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeRegionTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingBeforeSingleLineComments {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeSingleLineComments"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeSingleLineComments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeStructs {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeStructs"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeStructs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankLinePaddingBeforeUsingStatementBlocks {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeUsingStatementBlocks"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeUsingStatementBlocks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingBetweenPropertiesMultiLineAccessors {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBetweenPropertiesMultiLineAccessors"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBetweenPropertiesMultiLineAccessors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertBlankSpaceBeforeSelfClosingAngleBrackets {
            get {
                return ((bool)(this["Cleaning_InsertBlankSpaceBeforeSelfClosingAngleBrackets"]));
            }
            set {
                this["Cleaning_InsertBlankSpaceBeforeSelfClosingAngleBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertEndOfFileTrailingNewLine {
            get {
                return ((bool)(this["Cleaning_InsertEndOfFileTrailingNewLine"]));
            }
            set {
                this["Cleaning_InsertEndOfFileTrailingNewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnClasses {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnClasses"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnDelegates {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnDelegates"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnDelegates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnEnumerations {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnEnumerations"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnEnumerations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnEvents {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnEvents"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnFields {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnFields"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnInterfaces {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnInterfaces"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnMethods {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnMethods"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnProperties {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnProperties"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_InsertExplicitAccessModifiersOnStructs {
            get {
                return ((bool)(this["Cleaning_InsertExplicitAccessModifiersOnStructs"]));
            }
            set {
                this["Cleaning_InsertExplicitAccessModifiersOnStructs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Cleaning_PerformPartialCleanupOnExternal {
            get {
                return ((int)(this["Cleaning_PerformPartialCleanupOnExternal"]));
            }
            set {
                this["Cleaning_PerformPartialCleanupOnExternal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesAfterAttributes {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesAfterAttributes"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesAfterAttributes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesAfterOpeningBrace {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesAfterOpeningBrace"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesAfterOpeningBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesAtBottom {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesAtBottom"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesAtBottom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesAtTop {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesAtTop"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesAtTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesBeforeClosingBrace {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesBeforeClosingBrace"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesBeforeClosingBrace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesBeforeClosingTags {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesBeforeClosingTags"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesBeforeClosingTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankLinesBetweenChainedStatements {
            get {
                return ((bool)(this["Cleaning_RemoveBlankLinesBetweenChainedStatements"]));
            }
            set {
                this["Cleaning_RemoveBlankLinesBetweenChainedStatements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveBlankSpacesBeforeClosingAngleBrackets {
            get {
                return ((bool)(this["Cleaning_RemoveBlankSpacesBeforeClosingAngleBrackets"]));
            }
            set {
                this["Cleaning_RemoveBlankSpacesBeforeClosingAngleBrackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveEndOfFileTrailingNewLine {
            get {
                return ((bool)(this["Cleaning_RemoveEndOfFileTrailingNewLine"]));
            }
            set {
                this["Cleaning_RemoveEndOfFileTrailingNewLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveEndOfLineWhitespace {
            get {
                return ((bool)(this["Cleaning_RemoveEndOfLineWhitespace"]));
            }
            set {
                this["Cleaning_RemoveEndOfLineWhitespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RemoveMultipleConsecutiveBlankLines {
            get {
                return ((bool)(this["Cleaning_RemoveMultipleConsecutiveBlankLines"]));
            }
            set {
                this["Cleaning_RemoveMultipleConsecutiveBlankLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Cleaning_RemoveRegions {
            get {
                return ((int)(this["Cleaning_RemoveRegions"]));
            }
            set {
                this["Cleaning_RemoveRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RunVisualStudioFormatDocumentCommand {
            get {
                return ((bool)(this["Cleaning_RunVisualStudioFormatDocumentCommand"]));
            }
            set {
                this["Cleaning_RunVisualStudioFormatDocumentCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_RunVisualStudioRemoveAndSortUsingStatements {
            get {
                return ((bool)(this["Cleaning_RunVisualStudioRemoveAndSortUsingStatements"]));
            }
            set {
                this["Cleaning_RunVisualStudioRemoveAndSortUsingStatements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_SkipRemoveAndSortUsingStatementsDuringAutoCleanupOnSave {
            get {
                return ((bool)(this["Cleaning_SkipRemoveAndSortUsingStatementsDuringAutoCleanupOnSave"]));
            }
            set {
                this["Cleaning_SkipRemoveAndSortUsingStatementsDuringAutoCleanupOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_UpdateAccessorsToBothBeSingleLineOrMultiLine {
            get {
                return ((bool)(this["Cleaning_UpdateAccessorsToBothBeSingleLineOrMultiLine"]));
            }
            set {
                this["Cleaning_UpdateAccessorsToBothBeSingleLineOrMultiLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_UpdateEndRegionDirectives {
            get {
                return ((bool)(this["Cleaning_UpdateEndRegionDirectives"]));
            }
            set {
                this["Cleaning_UpdateEndRegionDirectives"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderCPlusPlus {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderCPlusPlus"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderCPlusPlus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderCSharp {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderCSharp"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderCSharp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderCSS {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderCSS"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderFSharp {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderFSharp"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderFSharp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderHTML {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderHTML"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderHTML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderJavaScript {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderJavaScript"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderJavaScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderJSON {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderJSON"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderJSON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderLESS {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderLESS"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderLESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderPHP {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderPHP"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderPHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderPowerShell {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderPowerShell"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderPowerShell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderR {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderR"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderSCSS {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderSCSS"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderSCSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderTypeScript {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderTypeScript"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderTypeScript"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderVB {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderVB"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderVB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderXAML {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderXAML"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderXAML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UpdateFileHeaderXML {
            get {
                return ((string)(this["Cleaning_UpdateFileHeaderXML"]));
            }
            set {
                this["Cleaning_UpdateFileHeaderXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Cleaning_UpdateSingleLineMethods {
            get {
                return ((bool)(this["Cleaning_UpdateSingleLineMethods"]));
            }
            set {
                this["Cleaning_UpdateSingleLineMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cleaning_UsingStatementsToReinsertWhenRemovedExpression {
            get {
                return ((string)(this["Cleaning_UsingStatementsToReinsertWhenRemovedExpression"]));
            }
            set {
                this["Cleaning_UsingStatementsToReinsertWhenRemovedExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Collapsing_CollapseSolutionWhenOpened {
            get {
                return ((bool)(this["Collapsing_CollapseSolutionWhenOpened"]));
            }
            set {
                this["Collapsing_CollapseSolutionWhenOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Collapsing_KeepSoloProjectExpanded {
            get {
                return ((bool)(this["Collapsing_KeepSoloProjectExpanded"]));
            }
            set {
                this["Collapsing_KeepSoloProjectExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_CenterOnWhole {
            get {
                return ((bool)(this["Digging_CenterOnWhole"]));
            }
            set {
                this["Digging_CenterOnWhole"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Digging_ComplexityAlertThreshold {
            get {
                return ((int)(this["Digging_ComplexityAlertThreshold"]));
            }
            set {
                this["Digging_ComplexityAlertThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int Digging_ComplexityWarningThreshold {
            get {
                return ((int)(this["Digging_ComplexityWarningThreshold"]));
            }
            set {
                this["Digging_ComplexityWarningThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int Digging_IndentationMargin {
            get {
                return ((int)(this["Digging_IndentationMargin"]));
            }
            set {
                this["Digging_IndentationMargin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Digging_PrimarySortOrder {
            get {
                return ((int)(this["Digging_PrimarySortOrder"]));
            }
            set {
                this["Digging_PrimarySortOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Digging_SecondarySortTypeByName {
            get {
                return ((bool)(this["Digging_SecondarySortTypeByName"]));
            }
            set {
                this["Digging_SecondarySortTypeByName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_ShowItemComplexity {
            get {
                return ((bool)(this["Digging_ShowItemComplexity"]));
            }
            set {
                this["Digging_ShowItemComplexity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_ShowItemMetadata {
            get {
                return ((bool)(this["Digging_ShowItemMetadata"]));
            }
            set {
                this["Digging_ShowItemMetadata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_ShowItemTypes {
            get {
                return ((bool)(this["Digging_ShowItemTypes"]));
            }
            set {
                this["Digging_ShowItemTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_ShowMethodParameters {
            get {
                return ((bool)(this["Digging_ShowMethodParameters"]));
            }
            set {
                this["Digging_ShowMethodParameters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Digging_SynchronizeOutlining {
            get {
                return ((bool)(this["Digging_SynchronizeOutlining"]));
            }
            set {
                this["Digging_SynchronizeOutlining"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Finding_ClearSolutionExplorerSearch {
            get {
                return ((bool)(this["Finding_ClearSolutionExplorerSearch"]));
            }
            set {
                this["Finding_ClearSolutionExplorerSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Finding_TemporarilyOpenSolutionFolders {
            get {
                return ((bool)(this["Finding_TemporarilyOpenSolutionFolders"]));
            }
            set {
                this["Finding_TemporarilyOpenSolutionFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentRunDuringCleanup {
            get {
                return ((bool)(this["Formatting_CommentRunDuringCleanup"]));
            }
            set {
                this["Formatting_CommentRunDuringCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Formatting_CommentSkipWrapOnLastWord {
            get {
                return ((bool)(this["Formatting_CommentSkipWrapOnLastWord"]));
            }
            set {
                this["Formatting_CommentSkipWrapOnLastWord"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Formatting_CommentWrapColumn {
            get {
                return ((int)(this["Formatting_CommentWrapColumn"]));
            }
            set {
                this["Formatting_CommentWrapColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlAlignParamTags {
            get {
                return ((bool)(this["Formatting_CommentXmlAlignParamTags"]));
            }
            set {
                this["Formatting_CommentXmlAlignParamTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlKeepTagsTogether {
            get {
                return ((bool)(this["Formatting_CommentXmlKeepTagsTogether"]));
            }
            set {
                this["Formatting_CommentXmlKeepTagsTogether"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlSpaceSingleTags {
            get {
                return ((bool)(this["Formatting_CommentXmlSpaceSingleTags"]));
            }
            set {
                this["Formatting_CommentXmlSpaceSingleTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlSpaceTags {
            get {
                return ((bool)(this["Formatting_CommentXmlSpaceTags"]));
            }
            set {
                this["Formatting_CommentXmlSpaceTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlSplitAllTags {
            get {
                return ((bool)(this["Formatting_CommentXmlSplitAllTags"]));
            }
            set {
                this["Formatting_CommentXmlSplitAllTags"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Formatting_CommentXmlSplitSummaryTagToMultipleLines {
            get {
                return ((bool)(this["Formatting_CommentXmlSplitSummaryTagToMultipleLines"]));
            }
            set {
                this["Formatting_CommentXmlSplitSummaryTagToMultipleLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Formatting_CommentXmlTagsToLowerCase {
            get {
                return ((bool)(this["Formatting_CommentXmlTagsToLowerCase"]));
            }
            set {
                this["Formatting_CommentXmlTagsToLowerCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Formatting_CommentXmlValueIndent {
            get {
                return ((int)(this["Formatting_CommentXmlValueIndent"]));
            }
            set {
                this["Formatting_CommentXmlValueIndent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_CacheFiles {
            get {
                return ((bool)(this["General_CacheFiles"]));
            }
            set {
                this["General_CacheFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool General_DiagnosticsMode {
            get {
                return ((bool)(this["General_DiagnosticsMode"]));
            }
            set {
                this["General_DiagnosticsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string General_Font {
            get {
                return ((string)(this["General_Font"]));
            }
            set {
                this["General_Font"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int General_IconSet {
            get {
                return ((int)(this["General_IconSet"]));
            }
            set {
                this["General_IconSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_LoadModelsAsynchronously {
            get {
                return ((bool)(this["General_LoadModelsAsynchronously"]));
            }
            set {
                this["General_LoadModelsAsynchronously"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_ShowStartPageOnSolutionClose {
            get {
                return ((bool)(this["General_ShowStartPageOnSolutionClose"]));
            }
            set {
                this["General_ShowStartPageOnSolutionClose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_SkipUndoTransactionsDuringAutoCleanupOnSave {
            get {
                return ((bool)(this["General_SkipUndoTransactionsDuringAutoCleanupOnSave"]));
            }
            set {
                this["General_SkipUndoTransactionsDuringAutoCleanupOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int General_Theme {
            get {
                return ((int)(this["General_Theme"]));
            }
            set {
                this["General_Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool General_UseUndoTransactions {
            get {
                return ((bool)(this["General_UseUndoTransactions"]));
            }
            set {
                this["General_UseUndoTransactions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Progressing_HideBuildProgressOnBuildStop {
            get {
                return ((bool)(this["Progressing_HideBuildProgressOnBuildStop"]));
            }
            set {
                this["Progressing_HideBuildProgressOnBuildStop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Progressing_ShowBuildProgressOnBuildStart {
            get {
                return ((bool)(this["Progressing_ShowBuildProgressOnBuildStart"]));
            }
            set {
                this["Progressing_ShowBuildProgressOnBuildStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Progressing_ShowProgressOnWindowsTaskbar {
            get {
                return ((bool)(this["Progressing_ShowProgressOnWindowsTaskbar"]));
            }
            set {
                this["Progressing_ShowProgressOnWindowsTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reorganizing_AlphabetizeMembersOfTheSameGroup {
            get {
                return ((bool)(this["Reorganizing_AlphabetizeMembersOfTheSameGroup"]));
            }
            set {
                this["Reorganizing_AlphabetizeMembersOfTheSameGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_ExplicitMembersAtEnd {
            get {
                return ((bool)(this["Reorganizing_ExplicitMembersAtEnd"]));
            }
            set {
                this["Reorganizing_ExplicitMembersAtEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Reorganizing_KeepMembersWithinRegions {
            get {
                return ((bool)(this["Reorganizing_KeepMembersWithinRegions"]));
            }
            set {
                this["Reorganizing_KeepMembersWithinRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Classes||12||Classes")]
        public string Reorganizing_MemberTypeClasses {
            get {
                return ((string)(this["Reorganizing_MemberTypeClasses"]));
            }
            set {
                this["Reorganizing_MemberTypeClasses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Constructors||2||Constructors")]
        public string Reorganizing_MemberTypeConstructors {
            get {
                return ((string)(this["Reorganizing_MemberTypeConstructors"]));
            }
            set {
                this["Reorganizing_MemberTypeConstructors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Delegates||4||Delegates")]
        public string Reorganizing_MemberTypeDelegates {
            get {
                return ((string)(this["Reorganizing_MemberTypeDelegates"]));
            }
            set {
                this["Reorganizing_MemberTypeDelegates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Destructors||3||Destructors")]
        public string Reorganizing_MemberTypeDestructors {
            get {
                return ((string)(this["Reorganizing_MemberTypeDestructors"]));
            }
            set {
                this["Reorganizing_MemberTypeDestructors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Enums||6||Enums")]
        public string Reorganizing_MemberTypeEnums {
            get {
                return ((string)(this["Reorganizing_MemberTypeEnums"]));
            }
            set {
                this["Reorganizing_MemberTypeEnums"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Events||5||Events")]
        public string Reorganizing_MemberTypeEvents {
            get {
                return ((string)(this["Reorganizing_MemberTypeEvents"]));
            }
            set {
                this["Reorganizing_MemberTypeEvents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fields||1||Fields")]
        public string Reorganizing_MemberTypeFields {
            get {
                return ((string)(this["Reorganizing_MemberTypeFields"]));
            }
            set {
                this["Reorganizing_MemberTypeFields"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Indexers||9||Indexers")]
        public string Reorganizing_MemberTypeIndexers {
            get {
                return ((string)(this["Reorganizing_MemberTypeIndexers"]));
            }
            set {
                this["Reorganizing_MemberTypeIndexers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Interfaces||7||Interfaces")]
        public string Reorganizing_MemberTypeInterfaces {
            get {
                return ((string)(this["Reorganizing_MemberTypeInterfaces"]));
            }
            set {
                this["Reorganizing_MemberTypeInterfaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Methods||10||Methods")]
        public string Reorganizing_MemberTypeMethods {
            get {
                return ((string)(this["Reorganizing_MemberTypeMethods"]));
            }
            set {
                this["Reorganizing_MemberTypeMethods"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Properties||8||Properties")]
        public string Reorganizing_MemberTypeProperties {
            get {
                return ((string)(this["Reorganizing_MemberTypeProperties"]));
            }
            set {
                this["Reorganizing_MemberTypeProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Structs||11||Structs")]
        public string Reorganizing_MemberTypeStructs {
            get {
                return ((string)(this["Reorganizing_MemberTypeStructs"]));
            }
            set {
                this["Reorganizing_MemberTypeStructs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Reorganizing_PerformWhenPreprocessorConditionals {
            get {
                return ((int)(this["Reorganizing_PerformWhenPreprocessorConditionals"]));
            }
            set {
                this["Reorganizing_PerformWhenPreprocessorConditionals"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_PrimaryOrderByAccessLevel {
            get {
                return ((bool)(this["Reorganizing_PrimaryOrderByAccessLevel"]));
            }
            set {
                this["Reorganizing_PrimaryOrderByAccessLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RegionsIncludeAccessLevel {
            get {
                return ((bool)(this["Reorganizing_RegionsIncludeAccessLevel"]));
            }
            set {
                this["Reorganizing_RegionsIncludeAccessLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RegionsInsertKeepEvenIfEmpty {
            get {
                return ((bool)(this["Reorganizing_RegionsInsertKeepEvenIfEmpty"]));
            }
            set {
                this["Reorganizing_RegionsInsertKeepEvenIfEmpty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RegionsInsertNewRegions {
            get {
                return ((bool)(this["Reorganizing_RegionsInsertNewRegions"]));
            }
            set {
                this["Reorganizing_RegionsInsertNewRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RegionsRemoveExistingRegions {
            get {
                return ((bool)(this["Reorganizing_RegionsRemoveExistingRegions"]));
            }
            set {
                this["Reorganizing_RegionsRemoveExistingRegions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_ReverseOrderByAccessLevel {
            get {
                return ((bool)(this["Reorganizing_ReverseOrderByAccessLevel"]));
            }
            set {
                this["Reorganizing_ReverseOrderByAccessLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reorganizing_RunAtStartOfCleanup {
            get {
                return ((bool)(this["Reorganizing_RunAtStartOfCleanup"]));
            }
            set {
                this["Reorganizing_RunAtStartOfCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".cpp .h||.xaml .xaml.cs||.xml .xsd||.ascx .ascx.cs||.aspx .aspx.cs||.master .mast" +
            "er.cs||.cshtml .cshtml.cs")]
        public string Switching_RelatedFileExtensionsExpression {
            get {
                return ((string)(this["Switching_RelatedFileExtensionsExpression"]));
            }
            set {
                this["Switching_RelatedFileExtensionsExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ThirdParty_OtherCleaningCommandsExpression {
            get {
                return ((string)(this["ThirdParty_OtherCleaningCommandsExpression"]));
            }
            set {
                this["ThirdParty_OtherCleaningCommandsExpression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThirdParty_UseJetBrainsReSharperCleanup {
            get {
                return ((bool)(this["ThirdParty_UseJetBrainsReSharperCleanup"]));
            }
            set {
                this["ThirdParty_UseJetBrainsReSharperCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThirdParty_UseTelerikJustCodeCleanup {
            get {
                return ((bool)(this["ThirdParty_UseTelerikJustCodeCleanup"]));
            }
            set {
                this["ThirdParty_UseTelerikJustCodeCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ThirdParty_UseXAMLStylerCleanup {
            get {
                return ((bool)(this["ThirdParty_UseXAMLStylerCleanup"]));
            }
            set {
                this["ThirdParty_UseXAMLStylerCleanup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_BuildProgressToolWindow {
            get {
                return ((bool)(this["Feature_BuildProgressToolWindow"]));
            }
            set {
                this["Feature_BuildProgressToolWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CleanupActiveCode {
            get {
                return ((bool)(this["Feature_CleanupActiveCode"]));
            }
            set {
                this["Feature_CleanupActiveCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CleanupAllCode {
            get {
                return ((bool)(this["Feature_CleanupAllCode"]));
            }
            set {
                this["Feature_CleanupAllCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CleanupOpenCode {
            get {
                return ((bool)(this["Feature_CleanupOpenCode"]));
            }
            set {
                this["Feature_CleanupOpenCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CleanupSelectedCode {
            get {
                return ((bool)(this["Feature_CleanupSelectedCode"]));
            }
            set {
                this["Feature_CleanupSelectedCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CloseAllReadOnly {
            get {
                return ((bool)(this["Feature_CloseAllReadOnly"]));
            }
            set {
                this["Feature_CloseAllReadOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CollapseAllSolutionExplorer {
            get {
                return ((bool)(this["Feature_CollapseAllSolutionExplorer"]));
            }
            set {
                this["Feature_CollapseAllSolutionExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CollapseSelectedSolutionExplorer {
            get {
                return ((bool)(this["Feature_CollapseSelectedSolutionExplorer"]));
            }
            set {
                this["Feature_CollapseSelectedSolutionExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_CommentFormat {
            get {
                return ((bool)(this["Feature_CommentFormat"]));
            }
            set {
                this["Feature_CommentFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_FindInSolutionExplorer {
            get {
                return ((bool)(this["Feature_FindInSolutionExplorer"]));
            }
            set {
                this["Feature_FindInSolutionExplorer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_JoinLines {
            get {
                return ((bool)(this["Feature_JoinLines"]));
            }
            set {
                this["Feature_JoinLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_ReadOnlyToggle {
            get {
                return ((bool)(this["Feature_ReadOnlyToggle"]));
            }
            set {
                this["Feature_ReadOnlyToggle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_RemoveRegion {
            get {
                return ((bool)(this["Feature_RemoveRegion"]));
            }
            set {
                this["Feature_RemoveRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_ReorganizeActiveCode {
            get {
                return ((bool)(this["Feature_ReorganizeActiveCode"]));
            }
            set {
                this["Feature_ReorganizeActiveCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_SettingCleanupOnSave {
            get {
                return ((bool)(this["Feature_SettingCleanupOnSave"]));
            }
            set {
                this["Feature_SettingCleanupOnSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_SortLines {
            get {
                return ((bool)(this["Feature_SortLines"]));
            }
            set {
                this["Feature_SortLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_SpadeToolWindow {
            get {
                return ((bool)(this["Feature_SpadeToolWindow"]));
            }
            set {
                this["Feature_SpadeToolWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Feature_SwitchFile {
            get {
                return ((bool)(this["Feature_SwitchFile"]));
            }
            set {
                this["Feature_SwitchFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ReSharper disable </string>\r\n  <string>ReSharper enable </string>\r\n</Array" +
            "OfString>")]
        public global::System.Collections.Specialized.StringCollection Formatting_IgnoreLinesStartingWith {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Formatting_IgnoreLinesStartingWith"]));
            }
            set {
                this["Formatting_IgnoreLinesStartingWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingBeforeFieldsSingleLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingBeforeFieldsSingleLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingBeforeFieldsSingleLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cleaning_InsertBlankLinePaddingAfterFieldsSingleLine {
            get {
                return ((bool)(this["Cleaning_InsertBlankLinePaddingAfterFieldsSingleLine"]));
            }
            set {
                this["Cleaning_InsertBlankLinePaddingAfterFieldsSingleLine"] = value;
            }
        }
    }
}
