//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteveCadwallader.CodeMaid.Snooper
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SnooperResources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SnooperResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SteveCadwallader.CodeMaid.Snooper.SnooperResources", typeof(SnooperResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static System.Drawing.Bitmap Class
        {
            get
            {
                object obj = ResourceManager.GetObject("Class", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClassFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("ClassFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClassInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("ClassInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClassPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("ClassPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ClassProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("ClassProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Const
        {
            get
            {
                object obj = ResourceManager.GetObject("Const", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ConstFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("ConstFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ConstInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("ConstInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ConstPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("ConstPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap ConstProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("ConstProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Delegate
        {
            get
            {
                object obj = ResourceManager.GetObject("Delegate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DelegateFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("DelegateFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DelegateInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("DelegateInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DelegatePrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("DelegatePrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap DelegateProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("DelegateProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Enum
        {
            get
            {
                object obj = ResourceManager.GetObject("Enum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EnumFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("EnumFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EnumInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("EnumInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EnumPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("EnumPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EnumProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("EnumProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Event
        {
            get
            {
                object obj = ResourceManager.GetObject("Event", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EventFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("EventFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EventInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("EventInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EventPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("EventPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap EventProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("EventProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Interface
        {
            get
            {
                object obj = ResourceManager.GetObject("Interface", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InterfaceFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("InterfaceFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InterfaceInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("InterfaceInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InterfacePrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("InterfacePrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap InterfaceProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("InterfaceProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Method
        {
            get
            {
                object obj = ResourceManager.GetObject("Method", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap MethodFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("MethodFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap MethodInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("MethodInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap MethodPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("MethodPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap MethodProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("MethodProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Namespace
        {
            get
            {
                object obj = ResourceManager.GetObject("Namespace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Property
        {
            get
            {
                object obj = ResourceManager.GetObject("Property", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PropertyFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("PropertyFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PropertyInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("PropertyInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PropertyPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("PropertyPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap PropertyProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("PropertyProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Region
        {
            get
            {
                object obj = ResourceManager.GetObject("Region", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Struct
        {
            get
            {
                object obj = ResourceManager.GetObject("Struct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StructFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("StructFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StructInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("StructInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StructPrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("StructPrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap StructProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("StructProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap Variable
        {
            get
            {
                object obj = ResourceManager.GetObject("Variable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariableFriend
        {
            get
            {
                object obj = ResourceManager.GetObject("VariableFriend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariableInternal
        {
            get
            {
                object obj = ResourceManager.GetObject("VariableInternal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariablePrivate
        {
            get
            {
                object obj = ResourceManager.GetObject("VariablePrivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        internal static System.Drawing.Bitmap VariableProtected
        {
            get
            {
                object obj = ResourceManager.GetObject("VariableProtected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}